### PR TITLE
add hit'n'run

### PR DESCRIPTION
**Pull request by benomatis**

### CODE REVIEW

**Comment by kalacs** [comment]
Looks good to me at first sight but  I want to do a quick smoke test on it. I think I can merge this by the weekend.

**Comment by benomatis** [comment]
I realize more could be added, like filtering options to only retrieve entries with certain statuses, for example, or specific titles, but for the purpose I'm using it for (I'm creating a workflow to send me an email when all hit'n'runs clear), this should suffice.

Great work, by the way, thank you for creating this package!

**Comment by benomatis** [comment]
@kalacs the only thing I missed doing is updating the ReadMe - should I still do it or shall I open a separate PR for it?

**Comment by benomatis** [comment]
> @kalacs the only thing I missed doing is updating the ReadMe - should I still do it or shall I open a separate PR for it?

...added to the above (update the doc), will you publish a new release to npm as well please? Thank you.

**Comment by kalacs** [comment]
Thank you for your contribution! I will publish it some time in this week.

**Comment by benomatis** [comment]
@kalacs Sorry for being a pain, but it's still not pushed to npm, would you mind please doing it along with the other [recent](https://github.com/kalacs/ncore-api/pull/4) [changes](https://github.com/kalacs/ncore-api/pull/5)? Thanks so much in advance!

**Comment by kalacs** [comment]
@benomatis Sorry for being late with this and thank you for your patience and your contribution to this package!
[v0.6.0](https://www.npmjs.com/package/ncore-api/v/0.6.0)

**Comment by benomatis** [comment]
@kalacs I'm terribly sorry for the confusion, but have you seen my comment here by chance? https://github.com/kalacs/ncore-api/pull/4#issuecomment-1538939328

Looks like the updated packages are causing problems... :(

**Pull request merged**
